version: '3'
#-----------#
services:
  db:
    image: bitnami/mongodb:4.0.3
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=mydb
  backend:
    image: onboard/backend:latest
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "npm i && sleep 10 && node server"
